import './classes/components/game.component';
import './classes/components/space.component';
import './classes/components/invader.component';
import './classes/components/keyboardcontrols.component';
import './classes/components/missile.component';
import './classes/components/explosion.component';
import './classes/components/selfdestruct.component';
import './classes/components/ground.component';
import './classes/components/shoot-controls.component';